# Generated by Django 5.0.2 on 2024-04-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activation_token',
            field=models.CharField(default='5b2b6f1f-2317-4806-bf13-ea94ea549c42', max_length=50),
        ),
    ]
