# Generated by Django 5.0.2 on 2024-04-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activation_token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
