# Generated by Django 5.0.2 on 2024-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_reset_token_users_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
