# Generated by Django 5.0.2 on 2024-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activation_token',
            field=models.CharField(default='6dc9d8b8-9ccd-4697-bc2b-a10e270523bb', max_length=50, unique=True),
        ),
    ]
