# Generated by Django 5.0.2 on 2024-04-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activation_token',
            field=models.CharField(default='c5460c91-012a-4665-bdcc-8aa67bfe2a94', max_length=50, unique=True),
        ),
    ]
