# Generated by Django 5.0.2 on 2024-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_users_reset_token_alter_users_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='reset_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='session_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
